// Copyright © 2026 Saleem Abdulrasool <compnerd@compnerd.org>. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause

@_implementationOnly
internal import CWinHTTP

@_transparent
internal var ERROR_WINHTTP_INVALID_OPTION: DWORD {
  DWORD(CWinHTTP.ERROR_WINHTTP_INVALID_OPTION)
}

@_transparent
internal var INTERNET_DEFAULT_PORT: INTERNET_PORT {
  INTERNET_PORT(CWinHTTP.INTERNET_DEFAULT_PORT)
}

@_transparent
internal var INTERNET_SCHEME_HTTP: INTERNET_SCHEME {
  INTERNET_SCHEME(CWinHTTP.INTERNET_SCHEME_HTTP)
}

@_transparent
internal var INTERNET_SCHEME_HTTPS: INTERNET_SCHEME {
  INTERNET_SCHEME(CWinHTTP.INTERNET_SCHEME_HTTPS)
}

@_transparent
internal var SECURITY_FLAG_IGNORE_UNKNOWN_CA: DWORD {
  DWORD(CWinHTTP.SECURITY_FLAG_IGNORE_UNKNOWN_CA)
}

@_transparent
internal var WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY: DWORD {
  DWORD(CWinHTTP.WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY)
}

@_transparent
internal var WINHTTP_ACCESS_TYPE_NAMED_PROXY: DWORD {
  DWORD(CWinHTTP.WINHTTP_ACCESS_TYPE_NAMED_PROXY)
}

// Swift does not import the SDK's composite macro.
@_transparent
internal var WINHTTP_CALLBACK_FLAG_ALL_COMPLETIONS: DWORD {
  WINHTTP_CALLBACK_STATUS_SENDREQUEST_COMPLETE |
  WINHTTP_CALLBACK_STATUS_HEADERS_AVAILABLE |
  WINHTTP_CALLBACK_STATUS_DATA_AVAILABLE |
  WINHTTP_CALLBACK_STATUS_READ_COMPLETE |
  WINHTTP_CALLBACK_STATUS_WRITE_COMPLETE |
  WINHTTP_CALLBACK_STATUS_REQUEST_ERROR |
  WINHTTP_CALLBACK_STATUS_GETPROXYFORURL_COMPLETE |
  WINHTTP_CALLBACK_STATUS_GETPROXYSETTINGS_COMPLETE
}

@_transparent
internal var WINHTTP_CALLBACK_FLAG_HANDLES: DWORD {
  DWORD(CWinHTTP.WINHTTP_CALLBACK_FLAG_HANDLES)
}

@_transparent
internal var WINHTTP_CALLBACK_STATUS_DATA_AVAILABLE: DWORD {
  DWORD(CWinHTTP.WINHTTP_CALLBACK_STATUS_DATA_AVAILABLE)
}

@_transparent
internal var WINHTTP_CALLBACK_STATUS_GETPROXYFORURL_COMPLETE: DWORD {
  DWORD(CWinHTTP.WINHTTP_CALLBACK_STATUS_GETPROXYFORURL_COMPLETE)
}

@_transparent
internal var WINHTTP_CALLBACK_STATUS_GETPROXYSETTINGS_COMPLETE: DWORD {
  DWORD(CWinHTTP.WINHTTP_CALLBACK_STATUS_GETPROXYSETTINGS_COMPLETE)
}

@_transparent
internal var WINHTTP_CALLBACK_STATUS_HANDLE_CLOSING: DWORD {
  DWORD(CWinHTTP.WINHTTP_CALLBACK_STATUS_HANDLE_CLOSING)
}

@_transparent
internal var WINHTTP_CALLBACK_STATUS_HEADERS_AVAILABLE: DWORD {
  DWORD(CWinHTTP.WINHTTP_CALLBACK_STATUS_HEADERS_AVAILABLE)
}

@_transparent
internal var WINHTTP_CALLBACK_STATUS_READ_COMPLETE: DWORD {
  DWORD(CWinHTTP.WINHTTP_CALLBACK_STATUS_READ_COMPLETE)
}

@_transparent
internal var WINHTTP_CALLBACK_STATUS_REQUEST_ERROR: DWORD {
  DWORD(CWinHTTP.WINHTTP_CALLBACK_STATUS_REQUEST_ERROR)
}

@_transparent
internal var WINHTTP_CALLBACK_STATUS_SENDREQUEST_COMPLETE: DWORD {
  DWORD(CWinHTTP.WINHTTP_CALLBACK_STATUS_SENDREQUEST_COMPLETE)
}

@_transparent
internal var WINHTTP_CALLBACK_STATUS_WRITE_COMPLETE: DWORD {
  DWORD(CWinHTTP.WINHTTP_CALLBACK_STATUS_WRITE_COMPLETE)
}

@_transparent
internal var WINHTTP_DECOMPRESSION_FLAG_GZIP: DWORD {
  DWORD(CWinHTTP.WINHTTP_DECOMPRESSION_FLAG_GZIP)
}

@_transparent
internal var WINHTTP_DEFAULT_ACCEPT_TYPES: UnsafeMutablePointer<LPCWSTR?>? {
  nil
}

@_transparent
internal var WINHTTP_DISABLE_AUTHENTICATION: DWORD {
  DWORD(CWinHTTP.WINHTTP_DISABLE_AUTHENTICATION)
}

@_transparent
internal var WINHTTP_DISABLE_COOKIES: DWORD {
  DWORD(CWinHTTP.WINHTTP_DISABLE_COOKIES)
}

@_transparent
internal var WINHTTP_DISABLE_REDIRECTS: DWORD {
  DWORD(CWinHTTP.WINHTTP_DISABLE_REDIRECTS)
}

@_transparent
internal var WINHTTP_FLAG_ASYNC: DWORD {
  DWORD(CWinHTTP.WINHTTP_FLAG_ASYNC)
}

@_transparent
internal var WINHTTP_FLAG_AUTOMATIC_CHUNKING: DWORD {
  DWORD(CWinHTTP.WINHTTP_FLAG_AUTOMATIC_CHUNKING)
}

@_transparent
internal var WINHTTP_FLAG_SECURE: DWORD {
  DWORD(CWinHTTP.WINHTTP_FLAG_SECURE)
}

@_transparent
internal var WINHTTP_HEADER_NAME_BY_INDEX: LPCWSTR? {
  nil
}

@_transparent
internal var WINHTTP_IGNORE_REQUEST_TOTAL_LENGTH: DWORD {
  DWORD(CWinHTTP.WINHTTP_IGNORE_REQUEST_TOTAL_LENGTH)
}

// This sentinel is an address, never a callable Swift function value.
@_transparent
internal var WINHTTP_INVALID_STATUS_CALLBACK: UnsafeRawPointer? {
  UnsafeRawPointer(bitPattern: -1)
}

@_transparent
internal var WINHTTP_NO_ADDITIONAL_HEADERS: LPCWSTR? {
  nil
}

@_transparent
internal var WINHTTP_NO_HEADER_INDEX: LPDWORD? {
  nil
}

@_transparent
internal var WINHTTP_NO_PROXY_BYPASS: LPCWSTR? {
  nil
}

@_transparent
internal var WINHTTP_NO_PROXY_NAME: LPCWSTR? {
  nil
}

@_transparent
internal var WINHTTP_NO_REFERER: LPCWSTR? {
  nil
}

@_transparent
internal var WINHTTP_NO_REQUEST_DATA: LPVOID? {
  nil
}

@_transparent
internal var WINHTTP_OPTION_CONTEXT_VALUE: DWORD {
  DWORD(CWinHTTP.WINHTTP_OPTION_CONTEXT_VALUE)
}

@_transparent
internal var WINHTTP_OPTION_DECOMPRESSION: DWORD {
  DWORD(CWinHTTP.WINHTTP_OPTION_DECOMPRESSION)
}

@_transparent
internal var WINHTTP_OPTION_DISABLE_FEATURE: DWORD {
  DWORD(CWinHTTP.WINHTTP_OPTION_DISABLE_FEATURE)
}

@_transparent
internal var WINHTTP_OPTION_ENABLE_HTTP_PROTOCOL: DWORD {
  DWORD(CWinHTTP.WINHTTP_OPTION_ENABLE_HTTP_PROTOCOL)
}

@_transparent
internal var WINHTTP_OPTION_HTTP_PROTOCOL_USED: DWORD {
  DWORD(CWinHTTP.WINHTTP_OPTION_HTTP_PROTOCOL_USED)
}

@_transparent
internal var WINHTTP_OPTION_SECURITY_FLAGS: DWORD {
  DWORD(CWinHTTP.WINHTTP_OPTION_SECURITY_FLAGS)
}

@_transparent
internal var WINHTTP_PROTOCOL_FLAG_HTTP2: DWORD {
  DWORD(CWinHTTP.WINHTTP_PROTOCOL_FLAG_HTTP2)
}

@_transparent
internal var WINHTTP_PROTOCOL_FLAG_HTTP3: DWORD {
  DWORD(CWinHTTP.WINHTTP_PROTOCOL_FLAG_HTTP3)
}

@_transparent
internal var WINHTTP_QUERY_FLAG_NUMBER: DWORD {
  DWORD(CWinHTTP.WINHTTP_QUERY_FLAG_NUMBER)
}

@_transparent
internal var WINHTTP_QUERY_RAW_HEADERS_CRLF: DWORD {
  DWORD(CWinHTTP.WINHTTP_QUERY_RAW_HEADERS_CRLF)
}

@_transparent
internal var WINHTTP_QUERY_STATUS_CODE: DWORD {
  DWORD(CWinHTTP.WINHTTP_QUERY_STATUS_CODE)
}
